### ISSUE TITLE
Chrome debugging port error with repeated attempts

### ISSUE THREAD

**Issue by oganm** [rstudio/webshot2#1]
```r
for(i in 1:30){
    Sys.sleep(.1)
    webshot2::webshot("https://github.com/rstudio/webshot2",
                      file = glue::glue('{i}.png'),
                      delay = 0)
}
```

The code above takes 30 screenshots of this repository and saves it. As the loop starts working, it fails at an arbitrary iteration with the error 

```
Error in launch_chrome(path, args) : 
  Chrome debugging port not open after 10 seconds.
```

The `Sys.sleep` was added to possibly solve the issue but did not seem to help. I have experimented with as high as 2. It will fail regardless after a varying number of successful iterations.

The original use case is for creating a gif of the page with animation by incrementing the delay argument (unexpectedly works quite well apart from the error by the way. wouldn't expect the delay to be very precise)

Ubuntu 16.04
Chrome 72.0.3626.121
R 3.6

**Comment by wch** [comment]
I just pushed a change that may fix this. Can you test it out?

**Comment by oganm** [comment]
Away from the original machine where I saw the problem but it appears to work on my Windows. Will let you know once I get back to the ubuntu

**Comment by oganm** [comment]
Confirmed to work on the original Ubuntu machine.

**Comment by wch** [comment]
Great!

**Comment by wch** [comment]
@oganm You probably saw me post this code elsewhere, but I'm also posting it here for future reference.

This records a series of frames:

```R
library(chromote)
b <- ChromoteSession$new(width = 480, height = 360)
frames <- list()
cancel_save_screencast_frames <- b$Page$screencastFrame(callback_ = function(value) {
  frames[[length(frames) + 1]] <<- value
  cat(".")
})
b$Page$navigate("http://giphygifs.s3.amazonaws.com/media/73FzKOYDpp7VK/giphy.mp4")
b$Page$startScreencast(format = "png", everyNthFrame = 2)


# Stop after 6 seconds
later(
  function() {
    b$Page$stopScreencast()
    cancel_save_screencast_frames()

    lapply(seq_along(frames), function(i) {
      writeBin(jsonlite::base64_dec(frames[[i]]$data), sprintf("frame%02d.png", i))  
    })
    b$close()
    message("done")
  },
  6
)
```

**Comment by oganm** [comment]
I actually did not see that. Thanks!
