### ISSUE TITLE
Add argument to suppress "screenshot completed" messages

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/webshot2#24]
Because the "screenshot completed" message is called inside a promise chain, `suppressMessages()` can't suppress messages generated in `webshot()`, `rmdshot()`, etc.

``` r
library(webshot2)

suppressMessages({
    webshot2::webshot("https://tidyverse.org")
})
# https://tidyverse.org screenshot completed
```

![](https://i.imgur.com/CLZvXbg.png)

**Comment by wch** [comment]
I believe that this issues is the root cause: https://github.com/r-lib/later/issues/108

**Comment by mattwarkentin** [comment]
Came here to file the same issue. @gadenbuie did you ever find a solution?
