### ISSUE TITLE
Vignette with Shiny + Plotly? 

### ISSUE THREAD

**Issue by tvqt** [rstudio/webshot2#51]
Hi there! 

I was looking at the most viewed unanswered questions on StackOverflow, and two of the most viewed ones concern saving elements of a `shiny` app as a pdf ([here](https://stackoverflow.com/questions/38962125/plotly-to-pdf-report) and [here](https://stackoverflow.com/questions/48452067/download-pdf-table-from-a-datatable-created-in-a-shiny-app-with-r)). 

I was wanting to answer these questions, potentially using webshot2, however, I can't seem to get things working. Seeing as this seems to be a fairly common problem, perhaps a short vignette could be good for it? It's quite easy to get stuck in a tangled web of strange errors, as I have 😅. I could try writing it, though I would need assistance in proofreading/answering my dumb questions 😄

**Comment by gadenbuie** [comment]
Thanks @tvqt! I see the value in documenting that pattern somewhere... but I'm confused about how webshot2 is involved. Do you happen to have a blog? This would be an excellent topic to write about if you do 😉 (If you don't have a blog, you definitely have an excellent strategy for coming up with post topics.)

If you'd like assistance with writing the post or want to bounce ideas off of us, we'd be happy to chat in our new Shiny Discord server: https://discord.gg/yMGCamUMnS
